# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
apiVersion: v1
type: application
version: 0.1.1
name: fsharp-cloud-native-ml
description: A distributed API for Machine Learning inferencing
keywords:
  - Machine Learning
  - FSharp
home: github.com/johnpaulada
sources:
  - github.com/johnpaulada
maintainers:
  - name: John Paul Ada
    email: johnpaulada@gmail.com
    url: johnpaulada.github.io
# icon: A URL to an SVG or PNG image to be used as an icon (optional).
appVersion: 0.1.0