apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsharpml
  labels:
    app: fsharpml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fsharpml
  template:
    metadata:
      labels:
        app: fsharpml
    spec:
      containers:
      - name: fsharpml
        image: fsharp-cloud-native-ml:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
